---
version: "2"
plugins:
  gofmt:
    enabled: true
  golint:
    enabled: true
    config:
      min_confidence: 0.8
  govet:
    enabled: true
exclude_patterns:
  # glob patterns
  - "**/.dockerignore"
  - "**/.gitignore"
  - "**/go.mod"
  - "**/go.sum"
  - "**/*_test.go"
  - "**/mock_*.go"
  - "**/*.md"
  - "**/*.txt"
  - "**/*.yml"
  # project-specific folders
  - ".github/"
  - "assets/"
  - "build/"
  - "deployments/"
  - "docs/"
