---
version: "2"
plugins:
  gofmt:
    enabled: true
  golint:
    enabled: true
    config:
      min_confidence: 0.8
  govet:
    enabled: true
exclude_patterns:
  - "**/*_test.go"
  - "**/mock_*.go"
  - ".github/"
  - "assets/"
  - "build/"
  - "deployments/"
  - "docs/"
