FROM node:6-alpine

RUN apk add --update bash \
&& adduser -s /bin/bash -h /opt/teleirc -D -H teleirc -u 99999 -g 99999

WORKDIR /opt/teleirc
CMD ["node", "teleirc.js"]

COPY . /opt/teleirc
COPY config.js.example /opt/teleirc/config.js
RUN chown -R teleirc:teleirc /opt/teleirc

USER teleirc
RUN npm install
