FROM mhart/alpine-node:6

RUN apk add --update bash icu-dev openssl git perl python build-base \
&& apk add gosu --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ \
&& adduser -s /bin/bash -h /opt/teleirc -D -H teleirc


COPY . /opt/teleirc
COPY config.js.example /opt/teleirc/config.js
RUN chown -R teleirc:teleirc /opt/teleirc \
&& cd /opt/teleirc \
&& npm install

WORKDIR /opt/teleirc

CMD ["gosu", "teleirc", "node", "teleirc.js"]
